-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.calendar_connections (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  provider character varying NOT NULL CHECK (provider::text = ANY (ARRAY['google'::character varying, 'outlook'::character varying, 'apple'::character varying]::text[])),
  provider_account_id character varying,
  provider_account_email character varying,
  access_token text,
  refresh_token text,
  token_expires_at timestamp with time zone,
  calendar_id character varying,
  sync_enabled boolean DEFAULT true,
  auto_import_events boolean DEFAULT false,
  connected_at timestamp with time zone DEFAULT now(),
  last_synced_at timestamp with time zone,
  CONSTRAINT calendar_connections_pkey PRIMARY KEY (id),
  CONSTRAINT calendar_connections_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.conversation_context (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  message_history jsonb DEFAULT '[]'::jsonb,
  current_intent character varying,
  pending_action jsonb,
  session_id character varying,
  expires_at timestamp with time zone DEFAULT (now() + '01:00:00'::interval),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT conversation_context_pkey PRIMARY KEY (id),
  CONSTRAINT conversation_context_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.list_items (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  list_id uuid NOT NULL,
  content text NOT NULL,
  notes text,
  is_completed boolean DEFAULT false,
  completed_at timestamp with time zone,
  position integer DEFAULT 0,
  reminder_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT list_items_pkey PRIMARY KEY (id),
  CONSTRAINT list_items_list_id_fkey FOREIGN KEY (list_id) REFERENCES public.lists(id),
  CONSTRAINT list_items_reminder_id_fkey FOREIGN KEY (reminder_id) REFERENCES public.reminders(id)
);
CREATE TABLE public.lists (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  name character varying NOT NULL,
  description text,
  icon character varying,
  color character varying,
  is_archived boolean DEFAULT false,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT lists_pkey PRIMARY KEY (id),
  CONSTRAINT lists_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.media_attachments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  media_type character varying NOT NULL CHECK (media_type::text = ANY (ARRAY['image'::character varying, 'audio'::character varying, 'video'::character varying, 'document'::character varying]::text[])),
  file_url text NOT NULL,
  file_size integer,
  mime_type character varying,
  transcription text,
  extracted_text text,
  extracted_data jsonb,
  reminder_id uuid,
  list_item_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  processed_at timestamp with time zone,
  note_id uuid,
  CONSTRAINT media_attachments_pkey PRIMARY KEY (id),
  CONSTRAINT media_attachments_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT media_attachments_reminder_id_fkey FOREIGN KEY (reminder_id) REFERENCES public.reminders(id),
  CONSTRAINT media_attachments_list_item_id_fkey FOREIGN KEY (list_item_id) REFERENCES public.list_items(id),
  CONSTRAINT media_attachments_note_id_fkey FOREIGN KEY (note_id) REFERENCES public.user_notes(id)
);
CREATE TABLE public.notification_history (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  type character varying NOT NULL CHECK (type::text = ANY (ARRAY['reminder'::character varying, 'shared'::character varying, 'system'::character varying, 'calendar'::character varying]::text[])),
  content text NOT NULL,
  reminder_id uuid,
  list_id uuid,
  recipient_whatsapp_id character varying,
  recipient_telegram_id character varying,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'sent'::character varying, 'failed'::character varying, 'delivered'::character varying, 'permanently_failed'::character varying]::text[])),
  error_message text,
  retry_count integer DEFAULT 0,
  sent_at timestamp with time zone,
  delivered_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notification_history_pkey PRIMARY KEY (id),
  CONSTRAINT notification_history_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT notification_history_reminder_id_fkey FOREIGN KEY (reminder_id) REFERENCES public.reminders(id),
  CONSTRAINT notification_history_list_id_fkey FOREIGN KEY (list_id) REFERENCES public.lists(id)
);
CREATE TABLE public.reminders (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  title text NOT NULL,
  notes text,
  reminder_time timestamp with time zone NOT NULL,
  is_recurring boolean DEFAULT false,
  recurrence_rule text,
  recurrence_end_date timestamp with time zone,
  priority character varying DEFAULT 'medium'::character varying CHECK (priority::text = ANY (ARRAY['low'::character varying, 'medium'::character varying, 'high'::character varying]::text[])),
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'completed'::character varying, 'cancelled'::character varying, 'snoozed'::character varying]::text[])),
  snoozed_until timestamp with time zone,
  snooze_count integer DEFAULT 0,
  completed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT reminders_pkey PRIMARY KEY (id),
  CONSTRAINT reminders_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.shared_reminders (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  reminder_id uuid NOT NULL,
  sender_user_id uuid NOT NULL,
  recipient_whatsapp_id character varying NOT NULL,
  recipient_name character varying,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'sent'::character varying, 'failed'::character varying]::text[])),
  shared_at timestamp with time zone DEFAULT now(),
  sent_at timestamp with time zone,
  CONSTRAINT shared_reminders_pkey PRIMARY KEY (id),
  CONSTRAINT shared_reminders_reminder_id_fkey FOREIGN KEY (reminder_id) REFERENCES public.reminders(id),
  CONSTRAINT shared_reminders_sender_user_id_fkey FOREIGN KEY (sender_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.user_notes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  title character varying,
  content text NOT NULL,
  tags ARRAY DEFAULT '{}'::text[],
  category character varying DEFAULT 'general'::character varying,
  is_pinned boolean DEFAULT false,
  is_archived boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  media_count integer DEFAULT 0,
  CONSTRAINT user_notes_pkey PRIMARY KEY (id),
  CONSTRAINT user_notes_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  whatsapp_id character varying UNIQUE,
  phone_number character varying CHECK (phone_number::text ~ '^\+?[1-9]\d{1,14}$'::text),
  name character varying,
  timezone character varying DEFAULT 'UTC'::character varying,
  language character varying DEFAULT 'en'::character varying,
  default_reminder_time time without time zone DEFAULT '09:00:00'::time without time zone,
  notification_enabled boolean DEFAULT true,
  advance_notice_minutes integer DEFAULT 15,
  quiet_hours_enabled boolean DEFAULT false,
  quiet_hours_start time without time zone,
  quiet_hours_end time without time zone,
  quiet_hours_days ARRAY,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  last_active_at timestamp with time zone DEFAULT now(),
  notes_count integer DEFAULT 0,
  telegram_id character varying UNIQUE,
  CONSTRAINT users_pkey PRIMARY KEY (id)
);